<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE countries [

    <!ELEMENT countries (country*)>

    <!ELEMENT country (area, currency+, government, borders*)>

    <!ATTLIST country name ID #REQUIRED>

    <!ELEMENT area (#PCDATA)>

    <!ATTLIST area unit NMTOKEN #REQUIRED>

    <!ELEMENT currency (#PCDATA)>

    <!ELEMENT government EMPTY>

    <!ATTLIST government system NMTOKEN #IMPLIED>

    <!ELEMENT borders EMPTY>

    <!ATTLIST borders country IDREFS #IMPLIED>
]>

<countries>
    <country name="Spain">
        <area unit="km2">504,645</area>
        <currency> Euro </currency>
        <government system="Monarchy"></government>
        <borders country="France"></borders>
        <borders country="Portugal"></borders>
    </country>
    <country name="Portugal">
        <area unit="km2"> 92,212 </area>
        <currency> Euro </currency>
        <government system="Republic"></government>
        <borders country="Spain"></borders>
    </country>
    <country name="France">
        <area unit="km2"> 675,417 </area>
        <currency> Euro </currency>
        <government system="Republic" />
        <borders country="Spain"></borders>
        <borders country="Switzerland"></borders>
    </country>
    <country name="Switzerland">
        <area unit="km2"> 41,290 </area>
        <currency> Swiss Franc </currency>
        <government system="Republic"></government>
        <borders country="France"></borders>
    </country>
    <country name="United_Kingdom">
        <area unit="km2"> 243,610 </area>
        <currency> Pound Sterling </currency>
        <government system="Monarchy"></government>
    </country>
</countries>